---
new_page_extension: md
auto_deploy: false
admin_path: admin
webhook_url: 
sections:
- type: heading
  label: Content
- type: directory
  path: content/articles
  label: Articles
  create: all
  match: "**/*"
- type: directory
  path: content/issues
  label: Issues
  create: all
  match: "**/*"
- type: heading
  label: Website
- type: document
  path: content/pages/about
  label: About Us
- type: document
  path: content/pages/pressroom
  label: Press Room
- type: document
  path: content/pages/privacy
  label: Privacy Policy
- type: document
  path: content/pages/support
  label: Support Us
- type: document
  path: content/pages/tos
  label: Terms of use
upload_dir: static
public_path: ''
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
