---
new_page_extension: md
auto_deploy: false
admin_path: admin
webhook_url: 
sections:
- type: heading
  label: Content
- type: directory
  path: content/articles
  label: Articles
  create: all
  match: "**/*"
  templates:
  - article
- type: directory
  path: content/authors
  label: Authors
  create: all
  match: "**/*"
  templates:
  - author
- type: directory
  path: content/categories
  label: Categories
  create: all
  match: "**/*"
  templates:
  - category
- type: directory
  path: content/issues
  label: Issues
  create: all
  match: "**/*"
  templates:
  - issue
- type: heading
  label: Website
- type: document
  path: content/pages/about.md
  label: About Us
- type: document
  path: content/pages/pressroom.md
  label: Press Room
- type: document
  path: content/pages/privacy.md
  label: Privacy Policy
- type: document
  path: content/pages/support.md
  label: Support Us
- type: document
  path: content/pages/tos.md
  label: Terms of use
- type: heading
  label: Translations
- type: document
  path: i18n/en.json
  label: English
- type: document
  path: i18n/fr.json
  label: French
  match: "**/*"
- type: heading
  label: Unused translations
- type: document
  path: i18n/zh.json
  label: Chinese
  match: "**/*"
- type: document
  path: i18n/nl.json
  label: Dutch
  match: "**/*"
- type: document
  path: i18n/de.json
  label: German
  match: "**/*"
- type: document
  path: i18n/el.json
  label: Greek
  match: "**/*"
- type: document
  path: i18n/it.json
  label: Italian
  match: "**/*"
- type: document
  path: i18n/ja.json
  label: Japanese
  match: "**/*"
- type: document
  path: i18n/pt.json
  label: Portuguese
  match: "**/*"
- type: document
  path: i18n/ru.json
  label: Russian
  match: "**/*"
- type: document
  path: i18n/es.json
  label: Spanish
  match: "**/*"
upload_dir: static
public_path: ''
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
