name: infra

on:
  workflow_dispatch:
    inputs:
      foo:
        description: ''
        required: false
        default: 'bar'

  push:
    branches:
      - main
      - develop

    paths:
      - 'infra/**'
      - '.github/workflows/infra.yml'

env:
  ENV: ${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}
  AWS_REGION: 'eu-west-3' # paris

jobs:
  infra:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@master

      - name: 'AWS Creds [DEV]'
        if: env.ENV == 'dev'
        uses: 'aws-actions/configure-aws-credentials@v1'
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
          aws-region: ${{ env.AWS_REGION }}

      - name: 'AWS Creds [PROD]'
        if: env.ENV == 'prod'
        uses: 'aws-actions/configure-aws-credentials@v1'
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terragrunt
        uses: autero1/action-terragrunt@v0.1.0
        with:
          terragrunt_version: 0.35.12
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true

      - name: 'Setup Terraform'
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.11
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true

      - name: 'Apply Terragrunt'
        id: apply
        run: cd infra/live/$ENV && terragrunt run-all apply --terragrunt-non-interactive
