name: infra

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name of the proceedings to update'
        required: true
        default: 'PFIAS'

  push:
    branches:
      - main
      - develop


env:
  ENV: ${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}
  AWS_REGION: 'eu-west-3' # paris

jobs:
  infra:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]

    steps:
      - name: 🛎 Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ secrets.SUBMODULE_GIT_TOKEN }}

      - name: 'AWS Creds [DEV]'
        if: env.ENV == 'dev'
        uses: 'aws-actions/configure-aws-credentials@v1'
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
          aws-region: ${{ env.AWS_REGION }}

      - name: 'AWS Creds [PROD]'
        if: env.ENV == 'prod'
        uses: 'aws-actions/configure-aws-credentials@v1'
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Update submodules
        shell: bash
        run: |
          git submodule update --init --remote && git submodule foreach git config pull.rebase true && git checkout main && git pull origin main --allow-unrelated-histories
          cp -r ./submodules/${{ github.event.inputs.name }}/config.js ./infra/live/$ENV/config.js 

      - name: Setup Terragrunt
        uses: autero1/action-terragrunt@v0.1.0
        with:
          terragrunt_version: 0.35.12
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true

      - name: 'Setup Terraform'
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.11
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true

      - name: 'Apply Terragrunt'
        id: apply
        run: cd infra/live/$ENV && terragrunt run-all apply --terragrunt-non-interactive
